nilaoda/BBDown

BBDown/BBDown.csproj, BBDown/Directory.Build.props, nuget.config
支持 x64-ARM64(Aarch64) 交叉编译
- Windows x64 编译 Windows ARM64
- Linux x64 编译 Linux ARM64
Native 工具链不支持 x86 和 ARM(ARMv7)，不过个人认为没有必要再发布 win-x86、linux-arm 和 win-arm 这三个版本。此外暂不支持 macOS ARM64。
如需交叉编译，发布 arm64 需要使用 native x64-arm64 交叉工具链，对于 Windows 可由 vs developer command prompt 脚本自动配置，对于 linux 需要手动指定 linker 和 sysroot，例如：
```
dotnet publish -r linux-arm64 -c Release -p:CppCompilerAndLinker=clang-12 -p:SysRoot=/crossrootfs/arm64
```
建议配置 GitHub Actions 自动构建。
另外，linux 和 macOS 版本经过 nativeaot 编译后符号文件包含在二进制中导致分发体积很大，可以通过 `strip BBDown` 命令删除掉符号部分，即可从 100+MB 减小到 25MB。
=> Cross-compilation support

BBDown/Directory.Build.props
This may cause crashing at startup on non-Windows platforms.
=> Disable statical link on non-Windows platforms

.github/workflows/build_latest.yml, BBDown/BBDown.csproj, BBDown/BBDownAppHelper.cs, BBDown/BBDownAria2c.cs, BBDown/BBDownBangumiInfoFetcher.cs, BBDown/BBDownCheeseInfoFetcher.cs, BBDown/BBDownIntlBangumiInfoFetcher.cs, BBDown/BBDownNormalInfoFetcher.cs, BBDown/BBDownParser.cs, BBDown/BBDownSpaceVideoFetcher.cs, BBDown/BBDownSubUtil.cs, BBDown/BBDownUtil.cs, BBDown/Directory.Build.props, BBDown/IFetcher.cs, BBDown/Program.cs
- Upgrade to .NET 6
- Replace all WebClient with HttpClient
- Remove all blocking invocations
- Shrink size by 20%
=> .NET 6 and HttpClient migration

BBDown/BBDownMuxer.cs
-movflags faststart 将moov前移，使MP4文件更适合网络串流，MP4Box默认采用此行为。
=> Add faststart for ffmpeg

BBDown/BBDownParser.cs, BBDown/Program.cs
加入"--encoding-priority"选项，对视频流排序，编码相同的视频流使用默认的排序
例: `--encoding-priority "avc,av1"`, AVC>AV1>HEVC
=> 增加视频编码的选择优先级选项, #204

BBDown/Directory.Build.props
Reverts nilaoda/BBDown#275
Ilc compling against SIM should work now in newer package. See https://github.com/dotnet/runtime/pull/66084.
=> Revert "Fix ilc version"

.github/workflows/build_latest.yml
The SSL certificate in ubuntu 16.04 image has expired.
=> Use new cross build image for Linux arm64

BBDown/BBDownUtil.cs, BBDown/Program.cs
举例当前执行的地方有一个ffmpeg, 也应该得用上. 同时做了一些优化.
=> 寻找工具时需要包含工作目录.

BBDown/ConsoleQRCode.cs
=> fix: 命令行二维码颜色错误问题

BBDown/Program.cs
目前的版本读取BBDown.config配置文件，比如
BBDown.config文件
```
--debug
-app
--encoding-priority hevc,avc,av1
```
--encoding-priority 无法正常生效 
通过pr修复了这个问题（string option都无法通过配置文件生效）
主要是由于rootCommand.Parse这个api的特性导致，当不走配置文件，通过命令行获取args
假设命令行输入是：BBdown.exe https://www.bilibili.com/video/BV1Mv4y1N7yJ --encoding-priority hevc,avc,av1 -app
params string[] args 相当于下面的数组
```c#
var string[] argsArr = ["https://www.bilibili.com/video/BV1Mv4y1N7yJ","--encoding-priority","hevc,avc,av1","-app"]
var commandLineResult = rootCommand.Parse(args);
```
其中--encoding-priority和hevc,avc,av1是分开的,rootCommand.Parse解析正常
当走配置文件时，这个数组的切分是由File.ReadAllLines完成的，其中--encoding-priority hevc,avc,av1是一行，只形成了一个item，而对于rootCommand.Parse来说，没法正确解析--encoding-priority hevc,avc,av1这样一整个的输入。
```c#
var configArgs = …
```
=> fix(配置文件): 修复配置文件无法正确读取string参数

BBDown/Directory.Build.props
I think we still need stack trace for better diagnostics. 
Also disable static linking for lower size footprint.
=> Generate stack trace

BBDown.Core/Config.cs, BBDown.Core/Fetcher/BangumiInfoFetcher.cs, BBDown.Core/Parser.cs, BBDown.Core/Util/SubUtil.cs, BBDown/CommandLineInvoker.cs, BBDown/MyOption.cs, BBDown/Program.cs
解除B站区域限制 (--area, --host, --ep-host)
跳过AI字幕下载 (--skip-ai)
比特率升序(最小体积优先) (--bandwith-ascending)
新增一个获取字幕的接口(即 获取章节信息(https://api.bilibili.com/x/player/v2) 的接口), 一些其他地区的番剧可能需要使用到
=> 添加一些新功能 ,添加 '解除B站区域限制' 的支持

BBDown/BBDownAria2c.cs, BBDown/BBDownUtil.cs, BBDown/CommandLineInvoker.cs, BBDown/MyOption.cs, BBDown/Program.cs
- 添加aria2c命令行参数支持
- 将帮助信息的全角符号改为半角
- 把之前检测账号登录不小心改的 '!=' 改回 '=='
=> 添加aria2c命令行参数支持, 一些帮助信息更改

BBDown.Core/Parser.cs, BBDown/BBDownUtil.cs, BBDown/CommandLineInvoker.cs, BBDown/MyOption.cs, BBDown/Program.cs
- 修改了md/ss号的解析方式, 使港澳台区解析支持ss/md
- 添加替换upos服务器
- 修改`-intl`帮助信息, 避免误将港澳台内容用`-intl`解析
=> make biliplus support ss/md & replace upos host

BBDown.Core/Fetcher/SpaceVideoFetcher.cs, BBDown/BBDownUtil.cs, BBDown/Program.cs
fix https://github.com/nilaoda/BBDown/issues/594, https://github.com/nilaoda/BBDown/issues/588, https://github.com/nilaoda/BBDown/issues/579
=> fix space video

BBDown.Core/APP/Payload/playviewreq.proto, BBDown.Core/AppHelper.cs, BBDown.Core/Parser.cs, BBDown/Program.cs
- 现在app端可以下载8K, HDR, 杜比视界等, 不过flac还是不行
- 给`AudioInfoWithCodecId`添加了`BackupUrl`, 避免选择到pcdn和mcdn, 而无法使用`--upos-host`
=> 改进了app端的解析

BBDown.Core/Util/HTTPUtil.cs, BBDown/BBDownUtil.cs
fix https://github.com/nilaoda/BBDown/issues/676
=> update av parsing

BBDown/BBDownUtil.cs
fix https://github.com/nilaoda/BBDown/issues/695
=> fix av parsing

BBDown/BBDownMuxer.cs, BBDown/CommandLineInvoker.cs, BBDown/MyOption.cs, BBDown/Program.cs
增加了--simply-mux参数用于避免在混流时增加多余信息 close #742 
优化了pageNumberWithZero在视频数小于10时，没有在前面补0的情况
=> fix: close nilaoda#742 增加精简混流参数，和其他优化项

BBDown.Core/APP/Response/dmviewreply.proto, BBDown.Core/AppHelper.cs, BBDown.Core/Util/HTTPUtil.cs, BBDown.Core/Util/SubUtil.cs
未登录时web端无法获取任何字幕, 改为使用app端解析
由于b站的字幕链接需要`auth_key`鉴权, 改为使用`Google.Protobuf`对app端的字幕解析
fix #817
=> fix app subtitle download

BBDown/Program.cs
支持在 file pattern 中使用 `.` 或者 `-`
例如
```conf 
<publishDate:yyyy-MM-dd>
<publishDate:yyyy.MM.dd>
```
=> Fix: allow dot(.) and dash(-) in file pattern

BBDown/BBDownUtil.cs, BBDown/Program.cs
1. 增强 `GetVideoInfoAsync` 方法：
- 当只输入 EP/SS ID 时，先尝试按番剧查找，如果找不到则尝试按课程查找
- 添加了相应的错误处理和日志输出，提高用户体验
2. 扩展 `GetAvIdAsync` 方法：
- 新增对 `^cheese/(ep|ss)\d+` 格式的支持（正则表达式仅作为提示）
3. 代码优化：
- 更新了部分注释，提高代码可读性
- 微调了日志输出的位置，使其更加合理
- 在 `GetVideoInfoAsync` 中，通过捕获 `KeyNotFoundException` 来判断是否需要尝试按课程查找
- 在 `GetAvIdAsync` 中，新增了对 `cheese/` 开头 URL 的处理逻辑
1. 考虑添加 `.editorconfig` 文件，规范化代码格式，便于不同开发者在各自的 IDE 或编辑器中保持一致的代码风格
2. 建议使用代码分析工具（如 DeepSource）和 Visual Studio 的分析功能，处理项目中的警告和提示，进一步提高代码质量
- 解决了用户在输入课程 EP/SS ID 时遇到的解析失败问题 Fix #764
=> 优化课程和番剧 EP/SS ID 解析，提升用户体验

BBDown/BBDownMuxer.cs, BBDown/Program.cs
=> 元数据写入视频URL

BBDown.Core/Util/SubUtil.cs, BBDown/BBDownUtil.cs
根据 https://github.com/nilaoda/BBDown/issues/948#issuecomment-2473748876 将 `SubUtil.cs` 与 `BBDownUtil.cs` 中的 API 链接进行了修改，由此修复字幕获取问题
- Close #948
=> 使用 wbi 接口以修复字幕获取问题
